### ISSUE TITLE
Bayes factors output by BAGELp do not correspond to output by BAGEL

### ISSUE THREAD

**Issue by kdelint** [sb43/BAGELp#2]
When using BAGELp to analyze published data for which readcounts and Bayes factors (BF) are available (see http://tko.ccbr.utoronto.ca/) I noticed the BAGELp output differs from the BFs published. Small differences could be caused by the essential and nonessential control sets and the timepoints used for analyses, but BAGELp log2-BFs are on average less than 10% of the published values. Log2-BF values do show a good correlation with published values (R2=0.97), but with some strong outliers.

**Comment by sb43** [comment]
BAGELp seed is reproducible if you keep parameters identical.
Please note that BAGELp  outputs bayes factor mean values instead of sum in the original version.
Original implementation:
bayes_factor = sum([logratio_lookup[round(x * 100)] for x in foldchanges])
BAGELp implementation: 
bayes_factor = np.mean([logratio_lookup[round(x * 100)] for x in foldchanges])

Hope this explains the discrepancy.
